# Site settings
title: The First Law of Kipple
email: matt.a.elphy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog of a Third Year Computer Science student.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elphy.co.uk" # the base hostname & protocol for your site
twitter_username: maelphy
github_username:  maael

# Build settings
markdown: kramdown

# Defaults
defaults:
 -
  scope:
   path: ""
  values:
   author: "Matthew Elphick"
